version: '3'

services:
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn ssam_ezst.asgi:application --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ssam_ezst_user
      - POSTGRES_PASSWORD=ssam_ezst_password
      - POSTGRES_DB=ssam_ezst_dev

volumes:
  postgres_data: